const DISPLAY_ALERT = 'SHOW_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';
const USER_AUTH_BEGIN = 'USER_AUTH_BEGIN';
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
const LOGOUT_USER = 'LOGOUT_USER';

const GET_AMIIBOS_LOADING = 'GET_AMIIBOS_LOADING';
const GET_AMIIBOS_SUCCESS = 'GET_AMIIBOS_SUCCESS';
const GET_AMIIBOS_ERROR = 'GET_AMIIBOS_ERROR';

const FILTER_AMIIBOS_LOADING = 'FILTER_AMIIBOS_LOADING';
const FILTER_AMIIBOS_SUCCESS = 'FILTER_AMIIBOS_SUCCESS';
const FILTER_AMIIBOS_ERROR = 'FILTER_AMIIBOS_ERROR';

const GO_TO_PAGE = 'GO_TO_PAGE';
const NEXT_PAGE = 'NEXT_PAGE';
const PREV_PAGE = 'PREV_PAGE';

const SELECT_AMIIBO = 'SELECT_AMIIBO';
const CLEAR_AMIIBO = 'CLEAR_AMIIBO';
const SHOW_DETAILS = 'SHOW_DETAILS';
const HIDE_DETAILS = 'HIDE_DETAILS';

const FIND_AMIIBO = 'FIND_AMIIBO';

const UPDATE_AMIIBO_LIST = "UPDATE_AMIIBO_LIST";

export {
	DISPLAY_ALERT,
	CLEAR_ALERT,
	USER_AUTH_BEGIN,
	USER_AUTH_SUCCESS,
	USER_AUTH_ERROR,
	LOGOUT_USER,
	GET_AMIIBOS_LOADING,
	GET_AMIIBOS_SUCCESS,
	GET_AMIIBOS_ERROR,
	FILTER_AMIIBOS_LOADING,
	FILTER_AMIIBOS_SUCCESS,
	FILTER_AMIIBOS_ERROR,
	GO_TO_PAGE,
	NEXT_PAGE,
	PREV_PAGE,
	SELECT_AMIIBO,
	CLEAR_AMIIBO,
	SHOW_DETAILS,
	HIDE_DETAILS,
	UPDATE_AMIIBO_LIST,
	FIND_AMIIBO
};
