const DISPLAY_ALERT = 'SHOW_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';
const USER_AUTH_BEGIN = 'USER_AUTH_BEGIN';
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
const LOGOUT_USER = 'LOGOUT_USER';

const GET_AMIIBOS_LOADING = 'GET_AMIIBOS_LOADING';
const GET_AMIIBOS_SUCCESS = 'GET_AMIIBOS_SUCCESS';
const GET_AMIIBOS_ERROR = 'GET_AMIIBOS_ERROR';

const GO_TO_PAGE = 'GO_TO_PAGE';
const NEXT_PAGE = 'NEXT_PAGE';
const PREV_PAGE = 'PREV_PAGE';

const ADD_TO_COLLECTION_LOADING = 'ADD_TO_COLLECTION_LOADING';
const ADD_TO_COLLECTION_SUCCESS = 'ADD_TO_COLLECTION_SUCCESS';
const ADD_TO_COLLECTION_ERROR = 'ADD_TO_COLLECTION_ERROR';

const REMOVE_FROM_COLLECTION_LOADING = 'REMOVE_FROM_COLLECTION_LOADING';
const REMOVE_FROM_COLLECTION_SUCCESS = 'REMOVE_FROM_COLLECTION_SUCCESS';
const REMOVE_FROM_COLLECTION_ERROR = 'REMOVE_FROM_COLLECTION_ERROR';

const SELECT_AMIIBO = 'SELECT_AMIIBO';
const CLEAR_AMIIBO = 'CLEAR_AMIIBO';
const SHOW_DETAILS = 'SHOW_DETAILS';
const HIDE_DETAILS = 'HIDE_DETAILS';

export {
	DISPLAY_ALERT,
	CLEAR_ALERT,
	USER_AUTH_BEGIN,
	USER_AUTH_SUCCESS,
	USER_AUTH_ERROR,
	LOGOUT_USER,
	GET_AMIIBOS_LOADING,
	GET_AMIIBOS_SUCCESS,
	GET_AMIIBOS_ERROR,
	ADD_TO_COLLECTION_LOADING,
	ADD_TO_COLLECTION_SUCCESS,
	ADD_TO_COLLECTION_ERROR,
	REMOVE_FROM_COLLECTION_LOADING,
	REMOVE_FROM_COLLECTION_SUCCESS,
	REMOVE_FROM_COLLECTION_ERROR,
	GO_TO_PAGE,
	NEXT_PAGE,
	PREV_PAGE,
	SELECT_AMIIBO,
	CLEAR_AMIIBO,
	SHOW_DETAILS,
	HIDE_DETAILS,
};
