const DISPLAY_ALERT = 'SHOW_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';
const USER_AUTH_BEGIN = 'USER_AUTH_BEGIN';
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
const LOGOUT_USER = 'LOGOUT_USER';

const GET_AMIIBOS_LOADING = 'GET_AMIIBOS_LOADING';
const GET_AMIIBOS_SUCCESS = 'GET_AMIIBOS_SUCCESS';
const GET_AMIIBOS_ERROR = 'GET_AMIIBOS_ERROR';

// const GET_FIGURES_LOADING = 'GET_FIGURED_LOADING';
// const GET_FIGURES_SUCCESS = 'GET_FIGURED_SUCCESS';
// const GET_FIGURES_ERROR = 'GET_FIGURED_ERROR';

// const GET_CARDS_LOADING = 'GET_CARDS_LOADING';
// const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
// const GET_CARDS_ERROR = 'GET_CARDS_ERROR';

// const GET_YARN_LOADING = 'GET_YARN_LOADING';
// const GET_YARN_SUCCESS = 'GET_YARN_SUCCESS';
// const GET_YARN_ERROR = 'GET_YARN_ERROR';

const ADD_TO_COLLECTION_LOADING = 'ADD_TO_COLLECTION_LOADING';
const ADD_TO_COLLECTION_SUCCESS = 'ADD_TO_COLLECTION_SUCCESS';
const ADD_TO_COLLECTION_ERROR = 'ADD_TO_COLLECTION_ERROR';

const REMOVE_FROM_COLLECTION_LOADING = 'REMOVE_FROM_COLLECTION_LOADING';
const REMOVE_FROM_COLLECTION_SUCCESS = 'REMOVE_FROM_COLLECTION_SUCCESS';
const REMOVE_FROM_COLLECTION_ERROR = 'REMOVE_FROM_COLLECTION_ERROR';

export {
	DISPLAY_ALERT,
	CLEAR_ALERT,
	USER_AUTH_BEGIN,
	USER_AUTH_SUCCESS,
	USER_AUTH_ERROR,
	LOGOUT_USER,
	GET_AMIIBOS_LOADING,
	GET_AMIIBOS_SUCCESS,
	GET_AMIIBOS_ERROR,
	ADD_TO_COLLECTION_LOADING,
	ADD_TO_COLLECTION_SUCCESS,
	ADD_TO_COLLECTION_ERROR,
	REMOVE_FROM_COLLECTION_LOADING,
	REMOVE_FROM_COLLECTION_SUCCESS,
	REMOVE_FROM_COLLECTION_ERROR
};
